./runDescr.sh "Alir3z4/html2text"
echo 0
./runDescr.sh "KindDragon/vld"
echo 1
./runDescr.sh "OSGeo/OSGeoLive"
echo 2
./runDescr.sh "Synchro/PHPMailer"
echo 3
./runDescr.sh "brbeaird/SmartThings_MyQ"
echo 4
./runDescr.sh "btford/grunt-conventional-changelog"
echo 5
./runDescr.sh "clog-tool/clog-cli"
echo 6
./runDescr.sh "commitizen-tools/commitizen"
echo 7
./runDescr.sh "conventional-changelog/standard-version"
echo 8
./runDescr.sh "cookpete/auto-changelog"
echo 9
./runDescr.sh "dylang/changelog"
echo 10
./runDescr.sh "fabiospampinato/bump"
echo 11
./runDescr.sh "facebook/react-native"
echo 12
./runDescr.sh "frinyvonnick/gitmoji-changelog"
echo 13
./runDescr.sh "gabrielemariotti/changeloglib"
echo 14
./runDescr.sh "git-chglog/git-chglog"
echo 15
./runDescr.sh "github-changelog-generator/github-changelog-generator"
echo 16
./runDescr.sh "github-tools/github-release-notes"
echo 17
./runDescr.sh "google/dagger"
echo 18
./runDescr.sh "hippojay/plugin.video.plexbmc"
echo 19
./runDescr.sh "invertase/melos"
echo 20
./runDescr.sh "jstasiak/python-zeroconf"
echo 21
./runDescr.sh "lalitkapoor/github-changes"
echo 22
./runDescr.sh "lerna/lerna-changelog"
echo 23
./runDescr.sh "lob/generate-changelog"
echo 24
./runDescr.sh "microsoft/docker"
echo 25
./runDescr.sh "nodejs/changelog-maker"
echo 26
./runDescr.sh "olivierlacan/keep-a-changelog"
echo 27
./runDescr.sh "orhun/git-cliff"
echo 28
./runDescr.sh "pajapro/fastlane-plugin-changelog"
echo 29
./runDescr.sh "picklesdoc/pickles"
echo 30
./runDescr.sh "puppetlabs/puppetlabs-vcsrepo"
echo 31
./runDescr.sh "pyrech/composer-changelogs"
echo 32
./runDescr.sh "rafinskipg/git-changelog"
echo 33
./runDescr.sh "react-native-community/releases"
echo 34
./runDescr.sh "release-it/release-it"
echo 35
./runDescr.sh "th0r/npm-upgrade"
echo 36
./runDescr.sh "tomasbjerre/git-changelog-lib"
echo 37
./runDescr.sh "twoscoops/two-scoops-of-django-1.11"
echo 38
./runDescr.sh "zapmaker/GrblHoming"
echo 39
./runDescr.sh "zertrin/duplicity-backup.sh"
echo 40
